### ISSUE TITLE
用node.js写的pre-commit hook脚本里，如何取得本次commit的文件路径和填写的message呢？

### ISSUE THREAD

**Issue by cuixiping** [y8n/git-hooks-node#2]
如题。
用node.js写的pre-commit hook脚本里，如何取得本次commit的文件路径和填写的message呢？

**Comment by y8n** [comment]
@cuixiping  
获取本次commit的文件路径可以使用`git diff`，调整参数即可，可以参考下面的方法
https://github.com/y8n/git-hooks-node/blob/master/xgfe-ma/pre-commit.js#L45-L73
在pre-commit里是获取不到提交信息的，如果需要对提交信息进行校验，可以使用prepare-commit-msg或commit-msg这两个hook，可以参考 https://stackoverflow.com/questions/5393178/get-commit-message-in-git-hook 或者https://github.com/kentcdodds/validate-commit-msg/blob/master/lib/cli.js （一个专门校验commit message的库，读读这个代码就明白了）:smile:
